<div id="pagetit">Відео-інструкції по роботі з порталом</div>

<?php
$this->widget('application.extensions.videojs.EVideoJS', array(
    'options' => array(
        // Unique identifier, is autogenerated by default, useful for jQuery integrations.
        'id' => false,
        // Video and poster width in pixels
        'width' => 640,
        // Video and poster height in pixels
        'height' => 400,
        // Poster image absolute URL
        'poster' => '/images/video/proverka_First_Frame.png',
        // Absolute URL of the video in MP4 format
        'video_mp4' => '/images/video/proverka.mp4',
        // Absolute URL of the video in OGV format
        'video_ogv' => false,
        // Absolute URL of the video in WebM format
        'video_webm' => false,
        // Use Flash fallback player ?
        'flash_fallback' => true,
        // Address of custom Flash player to use as fallback
        'flash_player' => 'http://releases.flowplayer.org/swf/flowplayer-3.2.1.swf',
        // Show controls ?
        'controls' => true,
        // Preload video content ?
        'preload' => true,
        // Autostart the playback ?
        'autoplay' => false,
        // Show VideoJS support link ?
        'support' => false,
        // Show video download links ?
        'download' => false,
    ),
));
?>
<br />